### ISSUE TITLE
cimgui status

### ISSUE THREAD

**Issue by sonoro1234** [inkyblackness/imgui-go#10]
In response to your https://github.com/inkyblackness/imgui-go#alternatives

cimgui has changed since you dismissed using it.
Now it is autogenerated from any imgui version or branch you desire

**Comment by dertseha** [comment]
Heya, @sonoro1234 , thank you for your message!
Omar gave me a heads up as well about this change in cimgui - which is why I rephrased my reasoning to past tense :)

I may have a look at it, though, so far I'm still fine with the thin, manually written C-layer that this Go wrapper uses.
This may change if there's a sudden explosion in demand of this Go library, and/or a complete overhaul for future ImGui versions is necessary.

**Comment by sonoro1234** [comment]
I have been able to test without any extra work the docking or viewport branches.
