### ISSUE TITLE
Statement about cimgui not up to date

### ISSUE THREAD

**Issue by sonoro1234** [inkyblackness/imgui-go#100]
Hi,

I could see at the readme:

Extrawurst/cimgui. Reasons for dismissal at time of decision:

    Was using old API (1.5x), 1.6x was attempted
    Apparently semi-exposed the C++ API, especially through the structures
    Adding this adds another dependency 

This is no longer true: The C-binding is now programatically generated so it is always up to date.
You can even generate it for whatever branch and version you desire. You can include ImGui internal API if you need it, It provides json files with information relevant to functions, structs and enums in order to allow binding makers to regenerate their bindings programatically.

I am open to questions, suggestions to facilitate the making of your binding.

**Comment by dertseha** [comment]
Hello @sonoro1234 and thank you for your message!
I know that cimgui is nowadays different, which is why the introduction was reworded to "dismissal *at time of decision*". The first two sentences are also phrased in past tense.
Do you have a proposal how to phrase this more explicitly?

I am still avoiding to introduce cimgui because of the third reason: I want to avoid adding another dependency.

**Comment by sonoro1234** [comment]
> Do you have a proposal how to phrase this more explicitly?

Just to state that this is not happening now?


> I am still avoiding to introduce cimgui because of the third reason: I want to avoid adding another dependency.

It is a dependency that it is worthwhile having: You do the programatical binding generation once (in go languaje for example) and you get the benefit of remake it instantly in the future, when ImGui changes or you want to use docking branch or whatever is added. 

I am using it in https://github.com/sonoro1234/LuaJIT-ImGui and I have been able to rebind it many times.

**Comment by sonoro1234** [comment]
done!!
