### ISSUE TITLE
feat: MouseWheel

### ISSUE THREAD

**Issue by melaurent** [inkyblackness/imgui-go#125]
I have added a method to get the MouseWheel values from the IO, it is returned as a Vec2 where X is horizontal scroll, and y vertical scroll. 
I can create a merge request if people agree with the change
https://github.com/melaurent/imgui-go/commit/cd66becfd8ffdf1a77b00cef3256af039a45fc0d

**Comment by dertseha** [comment]
Hello there and thank you for the message!
Looking at the existing functions, there's `AddMouseWheelDelta(horizontal, vertical float32)` already. To have it symmetric regarding the axes, I'd go for `MouseWheel() (float32, float32)`, so, returning two raw floating point values.
From a gut feeling these are rather two separate values rather than a combined `vector` to do math with.

And yes, feel free to do a pull request :)
