### ISSUE TITLE
InputText support

### ISSUE THREAD

**Issue by iegomez** [inkyblackness/imgui-go#15]
Hi! Thanks for your great wrapper! Are you planing to include InputText to it?

I gave it a try yesterday, but it keeps crashing with this not so helpful error:
```
free(): invalid next size (fast)
```

This is what I added:
```go
//At WrapperConverter.go
func wrapStringPointer(value *string) (wrapped *C.char, finisher func()) {

	if value != nil {
		wrapped = C.CString(*value)
		finisher = func() {
			*value = C.GoString(wrapped)
			C.free(unsafe.Pointer(wrapped))
		} // nolint: gas
	} else {
		finisher = func() {}
	}
	return
}

...

// At imgui.go
// InputText handles user input.
func InputText(label string, buf *string, bufSize int64, flags int) bool {
	labelArg, labelFin := wrapString(label)
	defer labelFin()
	bufArg, bufFin := wrapStringPointer(buf)
	defer bufFin()
	//fmt.Printf("original: %v - %v - %v - %v\n", label, buf, bufSize, flags)
	//fmt.Printf("returned wrapped: %v - %v\n", labelArg, bufArg)
	return C.iggInputText(labelArg, bufArg, C.long(bufSize), C.int(flags)) != 0
}

...

//At imguiWrapper.h
extern IggBool iggInputText(const char* label, char* buf, long buf_size, int flags);
extern IggBool iggInputTextMultiline(const char* label, char* buf, long buf_size, IggVec2 const *size, int flags);

...

//At imguiWrapper.cpp
IggBool iggInputText(const char* label, char* buf, long buf_size, int flags)
{
   return ImGui::InputText(label, buf, buf_size, flags, NULL, NULL);
}

IggBool iggInputTextMultiline(const char* label, char* buf, long buf_size, IggVec2 const *size, int flags)
{
   Vec2Wrapper sizeArg(size);
   return ImGui::InputTextMultiline(label, buf, buf_size, *sizeArg, flags, NULL, NULL);
}
```
Apart from that, I created InputTextFlags.go to make flags available, you may check all the changes [here](https://github.com/iegomez/imgui-go).

Any ideas on what's the issue? Have you tried to implement this yourself?
Also, I just passed `NULL` for the callback and user data, but if you have an idea on how to deal with the callback, that'd be great.

Cheers!

**Comment by dertseha** [comment]
Heya, thank you for your message and support!
I haven't looked into InputText. Although I could use that in InkyBlackness - I did text input differently there (essentially: not at all, only via clipboard ;) ) - I was both under time constraint and the underlying issues that need to be solved were tricky in that time frame.
You are now stumbling over them :)

Still, with more experience with C <-> Go interaction, I know see possible issues, as well as solutions.
My primary guess why your code crashes is probably because of the wrapStringPointer:
1. I don't believe that it will actually "convert" the Go *string to a C *char, but rather take the pointed string, allocate a C string, use its pointer, and free that one again as soon as the finish() function is called.
2. I haven't looked at how ImGui::InputString() is expecting the input parameters, so there might be further requirements

As to how to solve that: I would need a few days until I can look into it. My guess is that some sort of dynamic allocated state object will be required... Though, this is a very early guess. Perhaps also something can be done with the callback system, though, callbacks from C into Go are tricky as well as I've learned. Not impossible, they just need more work.
My primary goal would also be to get rid of the bufferSize argument on the exported API - unless it is meant to limit the amount of characters the user can input (not just the typical C buffer size limitation).

Several decisions to be considered on these functions. Most likely a reason why I didn't need them so far :)
I'll come back to you on that.

**Comment by iegomez** [comment]
> I don't believe that it will actually "convert" the Go *string to a C *char, but rather take the pointed string, allocate a C string, use its pointer, and free that one again as soon as the finish() function is called.

Indeed, I looked at how you "passed" int and float pointers and tried to do the same. So as you say, I'm actually allocating a char pointer in C to which I give the string's value, and after modification I assign the value of the *char to my *string in Go, and then free the *char. As far as I know, passing pointers between C and Go is a nightmare in a general sense and has restrictions that would prevent a string pointer from being passed in the first place.

Continuing with the crash, it's behavior is quite weird: sometimes it'll crash on the first input letter, and other times it'll let me append 5, 10 or 20 characters before crashing. The error is consistent though.

As for the bufferSize, it's intended to limit the amount of characters, so I'm for exposing it in some way. Maybe default and verbose variants could be an option.

Anyway, those are my quick thoughts. Thanks for the response and I'll be glad to keep the discussion once you've thought about it.

**Comment by dertseha** [comment]
Welp, it took longer than expected, thank you for your patience.

I've spent some time to tackle the issue and it comes down to buffer allocation.
The key was to allocate a buffer according to the maximum size and then work with that.

You can follow my adventure in this branch: https://github.com/inkyblackness/imgui-go/tree/InputTextSupport

And because I wanted to avoid creating a half-implemented verbose method and make incompatible changes later, I even started with the callback system. The main editing works (single-line), the callback has yet to be able to modify state data. When all is done, multi-line is just a small extension.

I hope to continue on this branch later this week.

**Comment by dertseha** [comment]
All right, I have InputText (and multiline) implemented in the branch, mentioned above.
@iegomez , may I ask you to have a look at it - to figure out whether I missed something? (anyone else is of course also invited)

After some back-and-forth I finally settled on completely hiding the dynamic buffer allocation aspect.
Even for a basic implementation, some sort of character-copying is always necessary (from given string to underlying buffer before call, copying back after call return). So I figured there's no point in specifying some arbitrary number of bytes (!) to use internally for a buffer. Since internally, the control works with UTF-8 bytes, exposing this limit on the public API, next to a string type, would have been even more confusing.
As such, the `InputText*` functions now are always "buffer resizable" and handle the re-allocation internally. To Go (user) side doesn't even know about this behaviour. In my opinion this makes the API clearer and more clearly separated. The call API is only about strings, and the callback is only about UTF-8 bytes.

I'll wait for the upcoming Sunday, then I'll merge to master if there are no major issues.

**Comment by dertseha** [comment]
pull request started, for easier reference of extensions.

**Comment by iegomez** [comment]
Hi! Sorry for my lack of response, I’m on vacation right now and will be getting back in a couple of days. I’ll take a look then to ser if I can give any useful feedback, but thanks again for your great work!

**Comment by iegomez** [comment]
Hi and sorry again for the delay. I've just tested the branch and it seems to work fine when using the `InputTextV` or `InputTextMultilineV` variants and giving an explicit callback function. So something like this works:
```
if imgui.InputTextMultilineV("test", &testStr, imgui.Vec2{X: 0, Y: 0}, imgui.InputTextFlagsNone, cb) {
...
}
...
func cb(data imgui.InputTextCallbackData) int32 {
	return 0
}
```
But, if I change `cb` to `nil` or call the simple functions `InputText` or `InputTextMultiline`, it'll crash with a stacktrace that looks like this:
```
panic: Assertion failed!
File: imgui_widgets.cpp, Line 3148

Expression: callback != NULL


goroutine 1 [running, locked to thread]:
github.com/inkyblackness/imgui-go.glob..func1(0xc0000900c0, 0x10, 0xc0000b2000, 0x11, 0xc4c)
	/home/iegomez/go/src/github.com/inkyblackness/imgui-go/Assert.go:18 +0x1a7
github.com/inkyblackness/imgui-go.iggAssert(0x0, 0x61730e, 0x617280, 0xc4c)
	/home/iegomez/go/src/github.com/inkyblackness/imgui-go/Assert.go:31 +0xac
github.com/inkyblackness/imgui-go._cgoexpwrap_7969402becd2_iggAssert(0x0, 0x61730e, 0x617280, 0xc4c)
	_cgo_gotypes.go:2166 +0x45
github.com/inkyblackness/imgui-go._Cfunc_iggInputTextMultiline(0x18b2e20, 0x18b32a0, 0xc000000005, 0xc0000900b0, 0x40000, 0x0)
	_cgo_gotypes.go:1274 +0x4d
github.com/inkyblackness/imgui-go.InputTextMultilineV(0x5e43c9, 0x4, 0xc000048f58, 0x0, 0x0, 0x0, 0x0)
	/home/iegomez/go/src/github.com/inkyblackness/imgui-go/imgui.go:477 +0x162
main.main()
	/home/iegomez/go/src/github.com/iegomez/lds/imgui/main.go:74 +0x489
```

As you can see, the offending code is this check at imgui_widgets.cpp:
```
const bool is_resizable = (flags & ImGuiInputTextFlags_CallbackResize) != 0;
if (is_resizable)
        IM_ASSERT(callback != NULL); // Must provide a callback if you set the ImGuiInputTextFlags_CallbackResize flag!
```
From a quick look I gather you are always setting the `inputTextFlagsCallbackResize`, e.g. here:
```
func InputTextV(label string, text *string, flags int, cb InputTextCallback) bool {
	if text == nil {
		panic("text can't be nil")
	}
	labelArg, labelFin := wrapString(label)
	defer labelFin()
	state := newInputTextState(*text, cb)
	defer func() {
		*text = state.buf.toGo()
		state.release()
	}()

	return C.iggInputText(labelArg, (*C.char)(state.buf.ptr), C.uint(state.buf.size),
		C.int(flags|inputTextFlagsCallbackResize), state.key) != 0
}
```
Again, from a quick glance, I believe that the flag is needed to allow the dynamic resize of the buffer, so maybe a dummy callback when nil is given or something of the sort is necessary. That sounds a bit hacky though and there's probably a better solution.

On another note, I do like the idea of leaving max length and other details to the callback and indeed the API looks neat and concise, but I'm having some trouble to make things work as intended or I didn't read carefully how to do it. From the documentation, `InputTextFlagsCallbackCharFilter` should allow me to discard inputs, but there's no available view to the buffer, so I can't really tell the length for example. That means that calling `data.Buffer()` in this case panics.

If instead I use `InputTextFlagsCallbackAlways`, setting the event char to 0, setting the buffer as marked, returning 1, etc., don't modify the buffer at all, e.g. something like this doesn't limit the number of chars and allows me to keep writing freely:
```
func cb(data imgui.InputTextCallbackData) int32 {
	fmt.Printf("buff len: %d - char: %s - key: %d - flags: %d\n", len(data.Buffer()), string(data.EventChar()), data.EventKey(), data.EventFlag())
	if len(data.Buffer()) > 8 {
		data.SetEventChar(0)
		data.MarkBufferModified()
		return 1
	}
	return 0
}
```

Well, that's for now, I'll sure let you know if I find anything else. Thanks again for taking the time to implement this feature in particular and your awesome work in general.

Cheers!

**Comment by dertseha** [comment]
Thank you for the testing - And sorry for not doing the simple tests (crashes) myself. Callbacks can be skipped now, and callback data `.Buffer()` returns nil now in case the callback (such as char filter) doesn't provide it. I've also updated the documentation to specify in which callback which function is available.

As for limiting: The buffer is not available in the char filter, right, so what about this:
```
imgui.InputTextV("limited", &text, imgui.InputTextFlagsCallbackCharFilter, func(data imgui.InputTextCallbackData) int32 {
	if len(text) >= 10 {
		return 1
	}
	return 0
})
```
Since it is an immediate mode GUI, we can access the actual string in the lambda anyway. And limiting based on string length (rather than UTF-8 bytes count) feels better as well.

With a buffer size parameter, the automatic resizing won't work. And I want to avoid exposing buffer handling to the user, as it is too low-level. In Go land we're used to a dynamic memory allocation. With the benefit of having closures & lambdas, we can access the actual string in the callback directly.

What do you think?

**Comment by iegomez** [comment]
I fully agree on not exposing the limit, and my function was just an example, I was actually using `len(string(data.Buffer()))` on my tests for limiting based on bytecodes instead of bytes.

About the callback, if you believe there's no other way, then I guess anonymous functions are good enough. The thing is that we can't reuse common functionality and it can get verbose with many text inputs. You could always wrap the function to pass the string value though, as with http middlewares, so it doesn't get that bad. What are your thoughts on this?

I'll test current and any other changes on monday and let you know of anything else.

**Comment by dertseha** [comment]
Right, the anonymous function is a good compromise. And if there's some repetitive code, users can most likely create their wrappers to their liking.

I'll wait for your final tests on this to merge.

**Comment by iegomez** [comment]
I just tested the changes and everything seems fine. I have a question about this though:

```go
// You may change the bytes.
// If you do so, mark the buffer as modified with MarkBufferModified().
```
What's the preferred way of modifying the buffer?

Also, deleting and inserting bytes works fine unless you mess up offset or limit, which will panic. It's pretty obvious that it does, but maybe some added warning in the documentation may help. An alternative would be to have those functions return an error and check bounds in them before calling the underlying functions, returning the error if it'd be an out of bounds access and leaving the buffer untouched. Anyway, this is just a thought after I forgot to change a hardcoded limit and hit the panic, but it's totally fine as it is right now.

**Comment by dertseha** [comment]
Some unexpected delays later I could finally work on this again.
I've extended the documentation and also added limit checks on the buffer modification functions.
As the last modification, I now merged the branch.

Thank you very much for your feedback and support on this addition!
