### ISSUE TITLE
AddText can't change font.

### ISSUE THREAD

**Issue by wakels** [inkyblackness/imgui-go#152]
I use UTF8 string to AddText. but show '?'

**Comment by dertseha** [comment]
Hello there!
This message reads very similar to that of #24 - please refer to the solution there and see if this matches your issue.

**Comment by wakels** [comment]
The issue is imgui.Text is correct, only drawlist.AddText is Incorrect。drawlist = imgui.WindowDrawList()

**Comment by dertseha** [comment]
Do I understand you correctly: You tried the solution as written in #24 , and it does not work for `DrawList.AddText()` ?
If this is the case, then this is curious, because all `imgui.Text()` functions use `DrawList.AddText()` in the background.

May I ask you to show the problem in a code snippet or example application, for instance based on [imgui-go-examples](https://github.com/inkyblackness/imgui-go-examples)?

**Comment by wakels** [comment]
I redo "go build and it displays correctly,
thank you very much
Next I will check the reason.
