### ISSUE TITLE
Imgui v1.67 upgrade

### ISSUE THREAD

**Issue by Galaco** [inkyblackness/imgui-go#16]
Imgui was released a few days ago: [v1.67](https://github.com/ocornut/imgui/releases/tag/v1.67).
It would be useful for me if the bundled version were bumped to the latest release; as the Tab Bar API is now out of beta and in the release; something that I require (adding bindings for tabbar is a separate issue)

Since its a minor version bump (1.61->1.67) there shouldn't be any compatibility issues.

I'm happy to raise a PR myself for this if its reasonable.

**Comment by dertseha** [comment]
Heya Galaco! Thank you for your message!
Yes, if you like you can do a pull request with an update. As you said, they should be compatible with the existing API.

At one point in the future we can also consider refactoring the examples like they did in ImGui, since we now have two :) Though, that doesn't have to be part of your pull request.

**Comment by Galaco** [comment]
Awesome, sorry it took so long to raise. PR linked below.

#18

**Comment by dertseha** [comment]
Thank you! I hope to get to it this weekend.

**Comment by dertseha** [comment]
See review comments. Not yet ready.

**Comment by dertseha** [comment]
Pull request is through, upgrade tasks performed, and [v1.5.0](https://github.com/inkyblackness/imgui-go/releases/tag/v1.5.0) is released.
Thank you again!
