### ISSUE TITLE
Cant compile for x64 windows architecture. 

### ISSUE THREAD

**Issue by Mo0nbase** [inkyblackness/imgui-go#171]
Simply put im having trouble compiling this on all versions with the x64 windows mingw compiler i keep getting the error 

`g++: error: unrecognized command-line option '-mthreads'; did you mean '-pthread'?`

To make sure this wasn't a issue with my computer i attempted this with the [go-mingw](https://golangrepo.com/repo/x1unix-docker-go-mingw) docker image. With the command...

`sudo docker run --rm -it -v "$(pwd)":/tmp/build x1unix/go-mingw /bin/sh -c "cd /tmp/build && go build -v -o imguigo-x64-bin.exe"`

I realize that this is a library and its not meant to be compiled on its own however i get the same error when trying to compile it within a project which is a big problem.

**Comment by dertseha** [comment]
That's curious. Which version of mingw are you using?
I am running on a Win10 64-bit machine with `x86_64-7.3.0-posix-seh-rt_v5-rev0` , and here I can build the `imgui-go-examples` (and, in general, my imgui apps) without issues.

Though, the version of mingw is just a guess; Would you have more details how you build your app? Can you cross-test with `imgui-go-examples` ?

**Comment by gucio321** [comment]
@Mo0nbase try this whole command:
`GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ HOST=x86_64-w64-mingw32 go build -ldflags "-s -w -H=windowsgui -extldflags=-static" -p 4 -v -o YourExeName.exe`

**Comment by gucio321** [comment]
also, you may want to check this out: https://github.com/AllenDang/giu/issues/449

**Comment by gucio321** [comment]
an @dertseha you may want to add this file to your repo: https://github.com/AllenDang/giu/pull/453
because without this, imgui-go apps seems not working on windows at all

**Comment by dertseha** [comment]
Thank you for the comments. I'll try to summarize:

The original problem was about missing threads libraries.
As noted in https://github.com/AllenDang/giu/issues/449, this seems rather to be a installation problem on the build machine.
When running `go install` on the `imgui-go-examples` project, I can do that on an MS Windows machine without issues. While this sounds like a "works on my machine" solution, this is nothing the library itself can solve.

As for things without which apps don't "seem to work on windows at all" - I can also counter with both the examples project, as well as the inkyblackness/hacked project that was the first user of this library. Both installing and running is fine for them.
On the examples project, I evaluated both with `go install -tags 'glfw' .` as well as `go install -ldflags "-s -w -H=windowsgui -extldflags=-static" -tags 'glfw' .`
While the former adds dependencies to some .dll files from mingw (which, for instance, are part of the `hacked` release archive, making it deployable) - the latter does perform static linking and no further dependencies.
Similar to the comment on https://github.com/AllenDang/giu/pull/453 , these flags are something that should be set on application level, and not pre-fixed by some library.

I will close this issue here. If there are more concrete details, which can be pinpointed to the wrapper specifically, please provide them, ideally in combination with the examples project.
