### ISSUE TITLE
Possible to use input field elements without the simluated window? 

### ISSUE THREAD

**Issue by airtonix** [inkyblackness/imgui-go#186]
I have a screen for a game where the user enters parameters for the level creation.

I don't want the draggable window, is it possible to just render the ui elements without it?

**Comment by dertseha** [comment]
Hi there, thank you for your question.
All elements are bound to a window region, even if you didn't specify one. Because in this case, **Dear ImGui** uses a "default" window.

If the core issue is that the window should not be draggable, use the window creation flag `WindowFlagsNoMove`. If you want to avoid the section to look like a window with a title bar, you can also specify `WindowFlagsNoTitleBar`.
To completely hide the fact that there's a window, there's also `WindowFlagsNoBackground`.

If you are curious for more, there are many more flags, see here: https://github.com/inkyblackness/imgui-go/blob/44567f2af289573078d51719638e9b71c203e60e/Window.go#L22-L82

**Comment by airtonix** [comment]
Nah, for asthetic reasons i dont want any window at all, just the input elements.
