### ISSUE TITLE
imgui.Image's render as monochrome

### ISSUE THREAD

**Issue by emily33901** [inkyblackness/imgui-go#42]
Hello,
Sort of my first time trying to get something like this to work. Trying to render a texture with imgui using `imgui.Image` - however the output is monochrome (tinted by whatever tint color is).

Example:
![Image](https://i.f1ssi0n.com/BonyAchroniteYellowjacket.png)

Both of those 2 textures should be rendered in color but are monochromed somwhere between my call to Image() with the textureId and it drawing to the screen.

Also fails with the top image which is a framebuffer texture. Both of the 2 above textures render to the framebuffer texture just fine but the framebuffer texture itself gets monochromed (which i guess is consistent with the other textures).

Im using the glfw3 and opengl3 base but running opengl 4.1.

Any pointers to where to look or what to try would be appreciated.

**Comment by dertseha** [comment]
Hello @emily33901 - thank you for the issue and also your patience - I've been busy the past days, so I couldn't answer.

The reason is that from both of these textures, only the red channel is used - assuming you took the rendering (and shader) code from the `imgui-go-examples` project.
This is because the code is specialized for the textures and draw commands that imgui would provide. This is typically for the fonts-texture, and also for all the graphical elements (window border, ...) - For these, imgui sets a `Color` attribute for the vertex shader, and takes the red channel of the texture as the alpha factor in the fragment shader.

For images you need a more intelligent shader and/or rendering code.

The key here is the `TextureID` type, of which you pass an instance to the `imgui.Image()` call. Please also read the documentation on TextureID. This value is an arbitrary value that the render code needs to interpret. By "default" (the example code), this value is interpreted as OpenGL texture handle - using the default shader as described.
For your case, you need to transport the information "this is not a default monochrome texture, this one has its own color" via the TextureID. There are several possibilities how to do that.

I had the same problem and approached it this way: Since TextureID is based on `uintptr`, which in my cases is always 64bit, I had 32 bits to work with, as texture handles of OpenGL need only 32bit. Of these free 32bit, I chose 8 to identify the type of the image. For dedicated images, I use a separate image type constant, which then signals the rendering code to do it differently.
Have a look at my code here:
* renderer: switching on image type [here](https://github.com/inkyblackness/hacked/blob/f48e7640315ca2c3ef40205e83edc2a751255ede/ui/gui/Context.go#L329-L347)
* shader: switching on image type [here](https://github.com/inkyblackness/hacked/blob/f48e7640315ca2c3ef40205e83edc2a751255ede/ui/gui/Context.go#L148-L156) (same file)

(beware though that in this code, I am working with bitmaps, hence I am using two textures - one being the bitmap, one being the palette)

It comes down to augmenting the value of TextureID to signal to the renderer to behave differently.

Did this clarify things?

**Comment by emily33901** [comment]
Yeah that makes a lot of sense, hadn't really thought about that. thank you

**Comment by quillaja** [comment]
I know this is a closed issue, but I wanted to share a possible (easy) fix for the example renderer. I haven't extensively used this "fix", but it seems to work with RGBA textures from Go `image.Image` and RGB textures from a Framebuffer object. I tried some TTF fonts in addition to the default font, and different color schemes, and didn't notice any artifacts.

1) in the [fragment shader line 244](https://github.com/inkyblackness/imgui-go-examples/blob/c1b02d18bfa157871169c90f812336193d1f0e72/internal/renderers/OpenGL3.go#L244), change the line to `Out_Color = Frag_Color * texture(Texture, Frag_UV);`

2) in `createFontsTexture()` change [L286](https://github.com/inkyblackness/imgui-go-examples/blob/c1b02d18bfa157871169c90f812336193d1f0e72/internal/renderers/OpenGL3.go#L286) from `image := io.Fonts().TextureDataAlpha8()` to `image := io.Fonts().TextureDataRGBA32()` to get a RGBA format texture from the font.

3) a few lines below that, alter the texture properties given when calling `gl.TexImage2D()` to reflect the new image format. That is, change 2 spots of `gl.R` to `gl.RGBA`.

**Comment by dertseha** [comment]
Well, it's not necessarily a "fix", it's rather a different approach. With the described changes, the texture is in full RGBA format and the shader uses the whole value.

Technically it is a viable version as well, with the "downside" of using up 4 times more memory. This may not be much with a standard ASCII-based character set, yet, enabling more regions, especially Asian ones, will make a larger dent in memory consumption.

The current implementation needs only one byte per pixel, as fonts (and their textures) are always monochrome.

**Comment by quillaja** [comment]
I might have found a method that will satisfy everyone. I was browsing the opengl wiki about textures and came across the [swizzle mask option](https://www.khronos.org/opengl/wiki/Texture#Swizzle_mask). It allows one to specify which channels from the source texture are used for the values of the R, G, B, and A channels during reads in shaders. In this case, we can store the font texture as a single byte in the R channel to save storage space using the gl.RED format, then have it swizzled to the A channel with RGB channels set to 1 in the shader. 

Just add this option when providing texture parameters around [L294](https://github.com/inkyblackness/imgui-go-examples/blob/c1b02d18bfa157871169c90f812336193d1f0e72/internal/renderers/OpenGL3.go#L294)

	swizzleMask := []int32{gl.ONE, gl.ONE, gl.ONE, gl.RED}
	gl.TexParameteriv(gl.TEXTURE_2D, gl.TEXTURE_SWIZZLE_RGBA, &swizzleMask[0])

The wiki seems to indicate that it's available since opengl v3.3.

Here's an image to demonstrate that the fonts look good, window alpha works (though kinda hard to see in the screenshot), and that the color texture in the "Raymarched render" shows in color.
![image](https://user-images.githubusercontent.com/17558269/87623707-e081e200-c6da-11ea-9f63-1527e34c5c5d.png)
